services:
    db:
        class: PDO
        arguments: ["mysql:dbname=%database_name%", "%database_user%", "%database_password%"]

    performance_factory:
        class: Mauro\TrainingBundle\Entity\Performance\PerformanceFactory

    performance_manager:
        class: Mauro\TrainingBundle\Entity\Performance\PerformanceManager
        arguments: ["@db", "@performance_factory"]
#    mauro_training.example:
#        class: Mauro\TrainingBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
